services:
  client:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - REACT_APP_SERVER_NAME=localhost
      - REACT_APP_SERVER_PORT=3000
    networks:
      - connection1
  server:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CLIENT_NAME=localhost
      - CLIENT_PORT=8000
      - DATABASE_NAME=redispubsub
    networks:
      - connection1
      - pubsub1
    depends_on:
      - redispubsub
  redispubsub:
    build: ./database
    ports:
      - "6379:6379"
    networks:
      - pubsub1

networks:
  connection1:
  pubsub1: